name: Push to docker hub

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1.1.0
        with:
          username: johnramsden
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: johnramsden/upmem
          tags: latest,2020.3.0
